blank_issues_enabled: false
contact_links:
  - name: Notifiarr Discord (#starrproxy)
    url: https://notifiarr.com/discord
    about: For support and questions, join the Notifiarr Discord and ask in the #starrproxy channel.
